In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [3]:
np.random.randint(50,size=100,high=101)

array([ 99,  56,  86,  82,  84,  80,  96,  52,  84,  67,  99,  81,  59,
        72,  77,  53,  83,  55,  92,  70,  74,  78,  99,  83,  63,  87,
        50,  70,  64,  97,  91,  93,  83,  76,  51,  85,  68,  75,  62,
        67,  78,  55,  78,  74,  52,  66,  57,  96,  58,  59,  93,  81,
        87,  63,  70,  66,  85,  65,  64,  67,  82,  91,  99,  64,  53,
        78,  96,  59,  62,  75,  67,  54,  65, 100,  78,  72,  77,  53,
        90, 100,  53,  72,  67,  78,  57,  95,  88,  71,  71,  51,  86,
        83,  58,  99,  81,  99,  77,  52,  78,  70])

In [4]:
np.random.randint(50,size=(50,5),high=101)

array([[ 62,  88,  59,  77,  92],
       [ 55,  84,  52,  74,  75],
       [ 64,  82,  85,  50,  58],
       [ 68,  70,  62,  79,  95],
       [ 65,  60,  77,  80,  84],
       [ 77,  75,  71,  50,  50],
       [ 61,  57,  63,  86,  53],
       [ 54,  80,  58,  53,  60],
       [ 96,  65,  94,  90,  94],
       [ 55,  82,  77,  82,  54],
       [ 96,  69,  81,  51,  94],
       [ 78,  81,  84,  58,  59],
       [ 79,  54,  58,  97,  59],
       [100,  92,  84,  86,  73],
       [ 78,  54,  76,  75,  64],
       [ 96,  96,  54,  52,  82],
       [ 58,  65,  60,  64,  97],
       [ 63,  68,  86,  90,  84],
       [ 80,  88,  89,  58,  64],
       [ 60,  60,  66,  65,  92],
       [ 70,  80,  89,  96,  71],
       [ 73,  85,  66,  69,  81],
       [ 96,  78,  65,  54,  54],
       [ 70,  90,  52,  80, 100],
       [ 70,  80,  78,  98,  50],
       [ 90,  61,  89,  65,  93],
       [ 80,  83,  62,  73,  84],
       [ 95,  77,  82,  66,  95],
       [ 57,  93,  97,  54,  71],
       [ 62,  

In [6]:
content = np.random.randint(50,size=(50,5),high=101)
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國文','英文','數學','地理','歷史'])
df1

國文  英文   數學   地理   歷史
1    72  99   83   83   75
2    62  82   74   89   83
3    63  53   77   89   58
4    59  95   66   87   79
5    77  98   57   86   92
6    96  86   54   89   88
7    53  71   70  100   99
8    64  64   66   85   91
9    84  65   59   60   61
10   57  55   59   91   96
11   50  62   68   89  100
12   90  70   96   59   53
13   62  56   77   55   52
14   76  98   61   79   71
15   67  60   56   81   50
16   64  51   71   86   82
17   94  59   87   89  100
18   61  73   87   60   90
19   76  90   85   78   76
20   71  63   91   59   50
21   72  73   57   52   63
22   67  69   50   94   76
23   69  64   77   73   68
24   65  68   70   74   93
25   54  90  100   69   86
26   59  58   77   59   84
27   79  86   53   60   99
28   61  64   91   55   58
29   99  99   81   74   51
30  100  89   74   93   73
31   77  69   99   55   91
32   86  71   65  100   80
33   52  96   68   76   90
34   93  52   63   65   79
35   66  51   97   53   50
36   95  55   87   73   52
37   99  89   63   58   80
38   61  82   66   62   57
39   73  72   81   78   69
40   66  84   81   95   73
41   59  92   66   75   70
42   69  74   84   85   57
43   82  51   84   68   91
44   69  98   66   52   95
45   61  92   83   98   96
46   67  92   71   91   64
47   72  93   90   79   51
48   93  73   70   68   95
49   80  62   96   60   60
50   97  51   83   55   96

In [7]:
df1['國文'] + df1['英文'] + df1['數學'] + df1['地理'] + df1['歷史']

1     412
2     390
3     340
4     386
5     410
6     413
7     393
8     370
9     329
10    358
11    369
12    368
13    302
14    385
15    314
16    354
17    429
18    371
19    405
20    334
21    317
22    356
23    351
24    370
25    399
26    337
27    377
28    329
29    404
30    429
31    391
32    402
33    382
34    352
35    317
36    362
37    389
38    328
39    373
40    399
41    362
42    369
43    376
44    380
45    430
46    385
47    385
48    399
49    358
50    382
dtype: int64

In [8]:
df1.to_excel('score.xlsx',sheet_name='2024_06_27')